version: "3"

services:
  mysql:
    image: mysql:5.7.31
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --server-id=1 --log-bin --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d:ro
    ports:
      - ${EXPOSED_MYSQL_PORT:-3306}:3306

volumes:
  mysql:
